[tasks.build]
command = "wasm-pack"
args = [ "build", "--dev", "--target", "web", "--out-name", "wasm", "--out-dir", "./static" ]
# watch = { ignore_pattern = "static/*" }

[tasks.compileStyle]
command = "sass"
args = [ "./styles/index.scss", "./static/style.css" ]

[tasks.serve]
command = "simple-http-server"
args = [ "-i", "./static/", "-p", "3000", "--nocache", "--try-file", "./static/index.html" ]